# Generated by Django 2.1.7 on 2019-02-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.RunSQL(
            """
            UPDATE main_run SET
              time = time / 1000, speed = speed / 1000;
        """
        )
    ]
