# Generated by Django 2.2.1 on 2019-05-09 12:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190222_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='geo_lookup',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
